// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;

using Foundation;
using AppKit;

using ForDuplicateDetection;

namespace DuplicateDetection
{
	public partial class DetectionViewController : NSViewController
	{
		public string TextValue
        {
			get;
			set;
        }

		public DetectionViewController (IntPtr handle) : base (handle)
		{
        }

		public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var detection = new ForDuplicateDetection.DuplicateDetection();
            detection.TextValue = this.TextValue;

            // メインウィンドウから受け取った値を外部ライブラリForDuplicateDetectionに渡し、重複していない値をTextViewにセット
            if(detection.NoDuplication().Length != 0)
            {
                this.detectionText1.Value = detection.NoDuplication();
            }

            // メインウィンドウから受け取った値を外部ライブラリForDuplicateDetectionに渡し、重複している値をTextViewにセット
            if (detection.Duplication().Length != 0)
            {
                this.detectionText2.Value = detection.Duplication();
            }
        }
    }
}
